apiVersion: v1
kind: Service
metadata:
  name: micro-api
  labels:
    name: micro-api
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: 'micro-api-port'
  selector:
    name: micro-api
