// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/jwt/jwt.proto

package go_micro_srv_jwt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewTokenRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTokenRequest) Reset()         { *m = NewTokenRequest{} }
func (m *NewTokenRequest) String() string { return proto.CompactTextString(m) }
func (*NewTokenRequest) ProtoMessage()    {}
func (*NewTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_976f9a388c6862c6, []int{0}
}

func (m *NewTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTokenRequest.Unmarshal(m, b)
}
func (m *NewTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTokenRequest.Marshal(b, m, deterministic)
}
func (m *NewTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTokenRequest.Merge(m, src)
}
func (m *NewTokenRequest) XXX_Size() int {
	return xxx_messageInfo_NewTokenRequest.Size(m)
}
func (m *NewTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NewTokenRequest proto.InternalMessageInfo

func (m *NewTokenRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type NewTokenResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresAt            int64    `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewTokenResponse) Reset()         { *m = NewTokenResponse{} }
func (m *NewTokenResponse) String() string { return proto.CompactTextString(m) }
func (*NewTokenResponse) ProtoMessage()    {}
func (*NewTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_976f9a388c6862c6, []int{1}
}

func (m *NewTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewTokenResponse.Unmarshal(m, b)
}
func (m *NewTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewTokenResponse.Marshal(b, m, deterministic)
}
func (m *NewTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewTokenResponse.Merge(m, src)
}
func (m *NewTokenResponse) XXX_Size() int {
	return xxx_messageInfo_NewTokenResponse.Size(m)
}
func (m *NewTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewTokenResponse proto.InternalMessageInfo

func (m *NewTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *NewTokenResponse) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func init() {
	proto.RegisterType((*NewTokenRequest)(nil), "go.micro.srv.jwt.NewTokenRequest")
	proto.RegisterType((*NewTokenResponse)(nil), "go.micro.srv.jwt.NewTokenResponse")
}

func init() { proto.RegisterFile("proto/jwt/jwt.proto", fileDescriptor_976f9a388c6862c6) }

var fileDescriptor_976f9a388c6862c6 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x2a, 0x2f, 0x01, 0x61, 0x3d, 0x30, 0x4f, 0x48, 0x20, 0x3d, 0x5f, 0x2f, 0x37,
	0x33, 0xb9, 0x28, 0x5f, 0xaf, 0xb8, 0xa8, 0x4c, 0x2f, 0xab, 0xbc, 0x44, 0x49, 0x8b, 0x8b, 0xdf,
	0x2f, 0xb5, 0x3c, 0x24, 0x3f, 0x3b, 0x35, 0x2f, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0x48,
	0x9c, 0x8b, 0xbd, 0xb4, 0x38, 0xb5, 0x28, 0x3e, 0x33, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33,
	0x88, 0x0d, 0xc4, 0xf5, 0x4c, 0x51, 0x0a, 0xe1, 0x12, 0x40, 0xa8, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b,
	0x4e, 0x15, 0x52, 0xe4, 0xe2, 0x49, 0x4c, 0x4e, 0x4e, 0x2d, 0x2e, 0x8e, 0x2f, 0x01, 0x89, 0x43,
	0x75, 0x70, 0x43, 0xc4, 0xc0, 0x4a, 0x85, 0x64, 0xb9, 0xb8, 0x52, 0x2b, 0x0a, 0x32, 0x8b, 0x52,
	0x8b, 0xe3, 0x13, 0x4b, 0x24, 0x98, 0x14, 0x18, 0x35, 0x98, 0x83, 0x38, 0xa1, 0x22, 0x8e, 0x25,
	0x46, 0x51, 0x5c, 0xcc, 0x5e, 0xe5, 0x25, 0x42, 0xc1, 0x5c, 0x1c, 0x30, 0xc3, 0x85, 0x14, 0xf5,
	0xd0, 0xdd, 0xa9, 0x87, 0xe6, 0x48, 0x29, 0x25, 0x7c, 0x4a, 0x20, 0x6e, 0x53, 0x62, 0x48, 0x62,
	0x03, 0x7b, 0xdb, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x98, 0x22, 0x20, 0x0d, 0x01, 0x00,
	0x00,
}
