// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/jwt/jwt.proto

package go_micro_api_jwt

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/micro/go-micro/api/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Jwt service

type JwtService interface {
	Call(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error)
}

type jwtService struct {
	c    client.Client
	name string
}

func NewJwtService(name string, c client.Client) JwtService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.api.jwt"
	}
	return &jwtService{
		c:    c,
		name: name,
	}
}

func (c *jwtService) Call(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error) {
	req := c.c.NewRequest(c.name, "Jwt.Call", in)
	out := new(proto1.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Jwt service

type JwtHandler interface {
	Call(context.Context, *proto1.Request, *proto1.Response) error
}

func RegisterJwtHandler(s server.Server, hdlr JwtHandler, opts ...server.HandlerOption) error {
	type jwt interface {
		Call(ctx context.Context, in *proto1.Request, out *proto1.Response) error
	}
	type Jwt struct {
		jwt
	}
	h := &jwtHandler{hdlr}
	return s.Handle(s.NewHandler(&Jwt{h}, opts...))
}

type jwtHandler struct {
	JwtHandler
}

func (h *jwtHandler) Call(ctx context.Context, in *proto1.Request, out *proto1.Response) error {
	return h.JwtHandler.Call(ctx, in, out)
}
