apiVersion: v1
kind: Service
metadata:
  name: micro-web
  labels:
    name: micro-web
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      targetPort: 'micro-web-port'
  selector:
    name: micro-web
