apiVersion: v1
kind: Service
metadata:
  name: nats-test
  labels:
    name: nats-test
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: nats-testp
  selector:
    name: nats-test
