apiVersion: v1
kind: Service
metadata:
  labels:
    name: sentinel
    role: service
  name: redis-sentinel
spec:
  type: LoadBalancer
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    redis-sentinel: 'true'
